"""Node entrypoints for ComfyUI-Anima-Enhancer."""

from .compat import (
    AnimaLayerReplayPatcher,
    NODE_CLASS_MAPPINGS as COMPAT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMPAT_NODE_DISPLAY_NAME_MAPPINGS,
)
from .phase2 import (
    AnimaIntermediateSpectrumPatcher,
    NODE_CLASS_MAPPINGS as PHASE2_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PHASE2_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(COMPAT_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PHASE2_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(COMPAT_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PHASE2_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = [
    "AnimaLayerReplayPatcher",
    "AnimaIntermediateSpectrumPatcher",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
